Repository code0-tech/pictor, pull requests merged in 2024-02, with the labels that each got.

#46 First implementation of popover
  .storybook/preview.ts
  __snapshots__/popover--popover-test-chromium.png
  __snapshots__/popover--popover-test-firefox.png
  __snapshots__/popover--popover-test-webkit.png
  package-lock.json
  package.json
  rollup.config.js
  src/components/popover/Popover.stories.tsx
  src/components/popover/Popover.style.scss
  src/components/popover/Popover.tsx
  src/utils/utils.ts
Labels: enhancement

#48 Menu component
  .storybook/preview.ts
  __snapshots__/badge--button-example-chromium.png
  __snapshots__/badge--button-example-firefox.png
  __snapshots__/badge--button-example-webkit.png
  __snapshots__/badge--variants-chromium.png
  __snapshots__/badge--variants-firefox.png
  __snapshots__/badge--variants-webkit.png
  __snapshots__/menu--menu-account-chromium.png
  __snapshots__/menu--menu-account-firefox.png
  __snapshots__/menu--menu-account-list-chromium.png
  __snapshots__/menu--menu-account-list-firefox.png
  __snapshots__/menu--menu-account-list-webkit.png
  __snapshots__/menu--menu-account-webkit.png
  src/components/badge/Badge.style.scss
  src/components/menu/InternalMenu.tsx
  src/components/menu/Menu.stories.tsx
  src/components/menu/Menu.style.scss
  src/components/menu/Menu.tsx
  src/components/popover/InternalPopover.tsx
  src/components/popover/Popover.style.scss
  src/components/popover/Popover.tsx
  src/styles/_helpers.scss
  src/utils/utils.ts
Labels: enhancement

#51 Allow to change screenshot selector
  .storybook/test-runner.ts
  __snapshots__/menu--menu-account-chromium.png
  __snapshots__/menu--menu-account-firefox.png
  __snapshots__/menu--menu-account-list-chromium.png
  __snapshots__/menu--menu-account-list-firefox.png
  __snapshots__/menu--menu-account-list-webkit.png
  __snapshots__/menu--menu-account-webkit.png
  src/components/menu/Menu.stories.tsx
Labels: enhancement

#54 Menu accessibility
  src/components/badge/Badge.style.scss
  src/components/menu/Menu.tsx
Labels: bug, enhancement, accessibility

#61 Update to LICENSE
  LICENSE
  package.json
Labels: enhancement

#59 Issue 30/more button styles
  src/components/button/Button.stories.tsx
  src/components/button/Button.style.scss
  src/components/button/Button.tsx
  src/components/card/Card.stories.tsx
  src/components/dropdown/Dropdown.stories.tsx
Labels: enhancement

#65 Multi select Component
  __snapshots__/multiselect--basic-multi-select-chromium.png
  __snapshots__/multiselect--basic-multi-select-firefox.png
  __snapshots__/multiselect--basic-multi-select-webkit.png
  __snapshots__/multiselect--basic-pill-chromium.png
  __snapshots__/multiselect--basic-pill-firefox.png
  __snapshots__/multiselect--basic-pill-webkit.png
  src/components/MultiSelect/MultiSelect.stories.tsx
  src/components/MultiSelect/MultiSelect.style.scss
  src/components/MultiSelect/MultiSelect.tsx
  src/components/pill/Pill.style.scss
  src/components/pill/Pill.tsx
Labels: enhancement

#66 New Type for Variants (Also for sizes now)
  __snapshots__/font--fonts-chromium.png
  __snapshots__/font--fonts-firefox.png
  __snapshots__/font--fonts-webkit.png
  __snapshots__/font--text-sizes-chromium.png
  __snapshots__/font--text-sizes-firefox.png
  __snapshots__/font--text-sizes-webkit.png
  src/components/FontSizes/Text.stories.tsx
  src/components/FontSizes/Text.style.scss
  src/components/FontSizes/Text.tsx
  src/components/alert/Alert.stories.tsx
  src/components/alert/Alert.tsx
  src/components/badge/Badge.stories.tsx
  src/components/badge/Badge.style.scss
  src/components/badge/Badge.tsx
  src/components/button/Button.stories.tsx
  src/components/button/Button.tsx
  src/components/card/Card.stories.tsx
  src/components/card/Card.style.scss
  src/components/card/Card.tsx
  src/components/menu/InternalMenu.tsx
  src/components/menu/Menu.stories.tsx
  src/components/menu/Menu.style.scss
  src/components/menu/Menu.tsx
  src/styles/_helpers.scss
  src/styles/_variables.scss
  src/utils/types.ts
  src/utils/utils.ts
Labels: enhancement

#78 60/missing spaceing on popver
  src/components/popover/InternalPopover.tsx
  src/components/popover/Popover.style.scss
Labels: bug
