Repository code0-tech/pictor, pull requests merged in 2024-05, with the labels that each got.

#86 Simple Flex component
  __snapshots__/flex--example-flex-chromium.png
  __snapshots__/flex--example-flex-firefox.png
  __snapshots__/flex--example-flex-webkit.png
  package.json
  src/components/flex/Flex.stories.tsx
  src/components/flex/Flex.style.scss
  src/components/flex/Flex.tsx
  src/index.ts
Labels: enhancement, regenerate-snapshots

#87 Update GitLab-Pipeline-Action to 1.8.0
  .github/workflows/ci.yml
  .github/workflows/update_snapshots.yml
Labels: dependencies

#88 switch logo to non requirements for quote component
  __snapshots__/quote--quote-sample-chromium.png
  __snapshots__/quote--quote-sample-firefox.png
  __snapshots__/quote--quote-sample-webkit.png
  src/components/quote/Quote.stories.tsx
  src/components/quote/Quote.tsx
Labels: enhancement, regenerate-snapshots

#90 Update node-playwright image
  .gitlab-ci.yml
  package-lock.json
  package.json
Labels: dependencies

#52 Implement needed Select Component
  .storybook/main.ts
  .storybook/test-runner.ts
  __snapshots__/select--basic-select-chromium.png
  __snapshots__/select--basic-select-firefox.png
  __snapshots__/select--basic-select-webkit.png
  package-lock.json
  package.json
  src/components/select/Select.stories.tsx
  src/components/select/Select.style.scss
  src/components/select/Select.tsx
  src/styles/_helpers.scss
  src/utils/utils.ts
Labels: enhancement

#110 Set rangeStrategy to bump for dev dependencies
  renovate.json
Labels: tooling

#125 Group rollup dependencies together
  renovate.json
Labels: tooling
